import {areas,vocabulary,kanaFamilies,grammar,scenarios,companions,curriculum,contentManifest,validateContent} from './data.js';
import {getState,update,exportSave,importSave,resetSave} from './state.js';
import {shuffle,mastery,skillScores,nextSkill,dueWords,weakWords,recordWord,recordKana,completeGrammar,completeConversation,achievementData,journeyItems,mistakeItems,dailyQuests,weeklyQuest,currentGrammar,activeCompanion,nodeUnlocked,nodeComplete,completeNode,nextCurriculumNode,curriculumProgress,stageLabel} from './engine.js';

const app=document.querySelector('#app');
let view='home',session=null,journalType='words',conversationTyping=true;
const nav=[['home','⌂','Home'],['learn','本','Learn'],['journal','言','Journal'],['garden','✿','Garden'],['stats','▥','Progress'],['companion','♡','Sakura']];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function level(){return Math.floor(getState().xp/100)+1}
function shell(content){const s=getState();return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">日</span><span>Nihongo <em>Quest</em></span></div><nav class="nav">${nav.map(n=>navButton(n)).join('')}</nav><div class="sidebar-bottom"><button class="companion-mini" data-go="companion"><img src="./assets/sakura-companion.webp" alt=""><div><strong>Sakura</strong><small>Your learning companion</small></div></button></div></aside><main class="main"><header class="topbar"><div><div class="eyebrow">Level ${level()} · ${s.studyDays.length} study days</div></div><div class="topstats"><span class="stat-pill">🔥 ${s.streak}</span><span class="stat-pill">✦ ${s.xp}</span><span class="stat-pill petal-pill">✿ ${masteredCount()}</span></div></header>${content}</main><nav class="mobile-nav">${nav.map(n=>navButton(n)).join('')}</nav></div>`}
function navButton([id,icon,label]){return `<button class="nav-btn ${view===id?'active':''}" data-nav="${id}"><span class="nav-icon">${icon}</span>${label}</button>`}
function render(){if(session){app.innerHTML=shell(renderSession());bindShell();bindSession();return}const renders={home:homeView,learn:learnView,journal:journalView,garden:gardenView,stats:statsView,companion:companionView,studio:studioView,settings:settingsView};app.innerHTML=shell((renders[view]||homeView)());bindShell();bindView()}
function bindShell(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{session=null;view=b.dataset.nav;render()});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{session=null;view=b.dataset.go;render()})}
function masteredCount(){return Object.values(getState().reviews).filter(r=>mastery(r)>=4).length}

function homeView(){const s=getState(),due=dueWords().length,weak=weakWords().length,quests=dailyQuests(),week=weeklyQuest(),mastered=masteredCount(),next=nextCurriculumNode();return `
 <section class="hero sakura-hero"><div class="hero-copy"><div class="hero-kicker">こんばんは · Today's Journey</div><h1>Small steps.<br>A brighter tomorrow.</h1><p>${due} words are ready to bloom. I’ve mixed your due reviews, recent mistakes and next kana into one focused journey.</p><button class="btn btn-primary" data-start="journey">Start today’s journey <span>→</span></button></div><div class="sakura-welcome"><img src="./assets/sakura-companion.webp" alt="Sakura, your learning companion"><div class="speech">Good to see you!<br><b>Let’s learn together.</b> ♡</div></div></section>
 <div class="learning-vitals"><div><span>🔥</span><b>${s.streak}</b><small>Day streak</small></div><div><span>✿</span><b>${mastered}</b><small>Blossoms</small></div><div><span>文</span><b>${Object.keys(s.grammar).length}</b><small>Grammar</small></div><div><span>💬</span><b>${Object.keys(s.conversations).length}</b><small>Stories</small></div></div>
 <div class="section"><div class="section-head"><h2>Continue your path</h2><span>${Math.round(curriculumProgress()*100)}% of current trail</span></div><button class="card path-next action-card" data-node="${next.id}"><span class="path-type">${nodeIcon(next.type)}</span><div><div class="eyebrow">${next.type} · ${next.area}</div><h3>${next.title}</h3><p>${next.outcome}</p></div><span class="path-arrow">→</span></button></div>
 <div class="grid grid-2 section"><div><div class="section-head"><h2>Quick practice</h2><span>Choose your focus</span></div><div class="grid grid-3">
   <button class="card action-card" data-start="review"><span class="action-icon">↻</span><h3>Smart Review</h3><p>${due} items due now, scheduled by mastery.</p></button>
   <button class="card action-card" data-start="mistakes"><span class="action-icon">◎</span><h3>Mistake Practice</h3><p>${weak?`${weak} weak words need attention.`:'Builds from patterns in your answers.'}</p></button>
   <button class="card action-card" data-start="kana"><span class="action-icon">あ</span><h3>Kana Training</h3><p>Progress row by row, with confusion drills.</p></button>
 </div></div><div><div class="section-head"><h2>Daily quests</h2><span>Resets daily</span></div><div class="card">${quests.map(q=>questRow(q)).join('')}</div></div></div>
 <div class="section"><div class="section-head"><h2>Your path</h2><span>Weekly quest: ${week.value}/${week.target} study days</span></div><div class="area-list">${areas.map(areaCard).join('')}</div></div>`}
function questRow(q){const p=Math.min(100,q.value/q.target*100);return `<div class="quest"><span class="quest-icon">${q.icon}</span><div><b>${q.label}</b><div class="bar"><span style="width:${p}%"></span></div></div><span class="quest-count">${Math.min(q.value,q.target)}/${q.target}</span></div>`}
function areaCard(a){const locked=getState().xp<a.unlock,words=a.groups.flatMap(g=>g.words),seen=words.filter(id=>getState().reviews[id]).length;return `<article class="card area-card"><div class="area-top"><span class="area-icon">${a.icon}</span><div><h3>${a.name}</h3><p>${a.description}</p></div></div><div class="bar"><span style="width:${seen/words.length*100}%;background:${a.color}"></span></div><div class="lesson-chips">${a.groups.map(g=>`<button class="chip" data-group="${g.id}" ${locked?'disabled':''}>${g.icon} ${g.name}</button>`).join('')}</div>${locked?`<div class="locked">🔒 Reach ${a.unlock} XP<br><small>${a.unlock-getState().xp} XP to go</small></div>`:''}</article>`}

function learnView(){const unlocked=currentGrammar();return `<div class="section-head"><div><div class="eyebrow">Structured learning</div><h1 class="page-title">Learning path</h1><p class="subtitle">Each chapter prepares the language you need for the story challenge ahead.</p></div></div>
 <section class="section"><div class="section-head"><h2>Adventure trail</h2><span>${curriculum.filter(nodeComplete).length}/${curriculum.length} chapters complete</span></div><div class="path-map">${curriculum.map((n,i)=>pathNode(n,i)).join('')}</div></section>
 <section class="section"><div class="section-head"><h2>Kana path</h2><span>Families unlock with progress</span></div><div class="kana-families">${kanaFamilies.map((f,i)=>kanaFamilyCard(f,i)).join('')}</div></section>
 <section class="section"><div class="section-head"><h2>Grammar trail</h2><span>${Object.keys(getState().grammar).length}/${grammar.length} structures learned</span></div><div class="grammar-grid">${grammar.map(g=>grammarCard(g,unlocked.some(x=>x.id===g.id))).join('')}</div></section>
 <section class="section"><div class="section-head"><h2>Conversation worlds</h2><label class="toggle"><input id="typingToggle" type="checkbox" ${conversationTyping?'checked':''}> Type my answers</label></div><div class="scenario-grid">${scenarios.filter(sc=>getState().xp>=areas.find(a=>a.id===sc.area).unlock).map(scenarioCard).join('')}</div></section>`}
function nodeIcon(type){return {kana:'あ',vocabulary:'言',grammar:'文',story:'💬'}[type]||'◆'}
function pathNode(n,i){const done=nodeComplete(n),open=nodeUnlocked(n);return `<div class="path-node ${done?'done':open?'open':'blocked'}"><div class="path-line"></div><button class="path-orb" data-node="${n.id}" ${open||done?'':'disabled'}>${done?'✓':nodeIcon(n.type)}</button><div class="card path-copy"><div class="eyebrow">Chapter ${i+1} · ${n.type}</div><h3>${n.title}</h3><p>${n.subtitle} · ${n.outcome}</p>${!open&&!done?`<small>Requires ${n.requires.map(id=>curriculum.find(x=>x.id===id)?.title).join(', ')}</small>`:''}</div></div>`}
function kanaFamilyCard(f,i){const unlocked=i<=Math.floor(getState().xp/100),total=f.items.reduce((n,[c])=>n+(getState().kana[c]?.correct||0),0);return `<button class="card action-card kana-family" data-family="${f.id}" ${unlocked?'':'disabled'}><span class="action-icon">${f.items[0][0]}</span><h3>${f.name} ${unlocked?'':'🔒'}</h3><div class="kana-row">${f.items.map(x=>x[0]).join(' ')}</div><p>${total} correct answers</p></button>`}
function grammarCard(g,unlocked){const learned=getState().grammar[g.id];return `<article class="card ${unlocked?'':'locked-card'}"><div class="grammar-symbol">${g.title}</div><h3>${g.summary}</h3><div class="pattern">${g.pattern}</div><p><b>${g.example}</b><br>${g.exampleEn}</p><div style="margin-top:14px">${learned?'<span class="learned">✓ In Grammar Journal</span>':unlocked?`<button class="btn btn-secondary btn-small" data-grammar="${g.id}">Mark lesson complete</button>`:'<span class="tag">Unlocks with more XP</span>'}</div></article>`}
function scenarioCard(sc){return `<button class="card action-card scenario-card" data-scenario="${sc.id}"><span class="place">${sc.icon}</span><h3>${sc.place}</h3><p>Talk with ${sc.npc}</p></button>`}

function journalView(){const words=vocabulary.filter(w=>getState().reviews[w.id]),learned=grammar.filter(g=>getState().grammar[g.id]);return `<div><div class="eyebrow">Your collection</div><h1 class="page-title">Journal</h1><p class="subtitle">Every answer shapes mastery and the next review date.</p></div><div class="journal-tools"><button class="btn ${journalType==='words'?'btn-primary':'btn-ghost'} btn-small" data-journal="words">Word Journal · ${words.length}</button><button class="btn ${journalType==='grammar'?'btn-primary':'btn-ghost'} btn-small" data-journal="grammar">Grammar Journal · ${learned.length}</button><input id="journalSearch" class="input search" placeholder="Search Japanese or English…"></div><div id="journalResults">${journalType==='words'?wordCards(words):grammarJournal(learned)}</div>`}
function wordCards(words){if(!words.length)return `<div class="card empty">Words appear here as soon as you meet them in a lesson or journey.</div>`;return `<div class="word-grid">${words.map(wordCard).join('')}</div>`}
function wordCard(w){const r=getState().reviews[w.id],m=mastery(r),skills=skillScores(r);return `<article class="card word-card" data-search="${esc(`${w.kana} ${w.kanji} ${w.romaji} ${w.meaning} ${w.category}`.toLowerCase())}"><div class="word-jp"><div><span class="kana">${w.kana}</span><div class="kanji">${getState().settings.furigana?w.kanji:''}</div></div><button title="Hear pronunciation" aria-label="Hear ${w.kana}" data-speak="${w.kana}">♪</button></div>${getState().settings.romaji?`<div class="romaji">${w.romaji}</div>`:''}<div class="meaning">${w.meaning}</div><span class="tag">${w.category}</span><div class="example"><b>${w.example}</b><br>${w.exampleEn}</div><div class="mastery" title="Mastery ${m} of 5">${[1,2,3,4,5].map(i=>`<i class="${i<=m?'on':''}"></i>`).join('')}</div><div class="skill-mini">${Object.entries(skills).map(([k,v])=>`<span title="${k} ${v}%"><i style="height:${Math.max(3,v/2)}%"></i>${k[0].toUpperCase()}</span>`).join('')}</div></article>`}
function grammarJournal(items){if(!items.length)return `<div class="card empty">Complete a grammar lesson to add its pattern and example here.</div>`;return `<div class="grammar-grid">${items.map(g=>`<article class="card" data-search="${esc((g.title+' '+g.summary).toLowerCase())}"><div class="grammar-symbol">${g.title}</div><h3>${g.summary}</h3><div class="pattern">${g.pattern}</div><p><b>${g.example}</b><br>${g.exampleEn}</p></article>`).join('')}</div>`}

function gardenView(){const s=getState(),blossoms=masteredCount(),chapters=curriculum.filter(nodeComplete).length,stories=Object.keys(s.conversations).length,kana=Object.values(s.kana).filter(x=>(x.correct||0)>=5).length,nextBloom=Math.max(1,5-(blossoms%5));return `<div><div class="eyebrow">Your learning journey in bloom</div><h1 class="page-title">Sakura Garden</h1><p class="subtitle">Everything here grows from something you have learned.</p></div><section class="garden-scene section" style="--bloom:${Math.min(100,18+blossoms*7)}%"><img src="./assets/sakura-garden.webp" alt="Moonlit Japanese garden with a cherry blossom tree"><div class="garden-shade"></div><div class="garden-level"><span>Garden level</span><b>${Math.floor((chapters+blossoms)/3)+1}</b></div><div class="garden-caption"><h2>${blossoms?'Your tree is flourishing':'Your first blossom is waiting'}</h2><p>${nextBloom} more mastered ${nextBloom===1?'word':'words'} until the next garden gift.</p><div class="garden-progress"><span style="width:${(5-nextBloom)/5*100}%"></span></div></div></section><div class="garden-ledger section"><div class="card"><span>🌿</span><b>${chapters}</b><small>Branches · chapters</small></div><div class="card"><span>🌸</span><b>${blossoms}</b><small>Blossoms · words</small></div><div class="card"><span>🏮</span><b>${stories}</b><small>Lanterns · stories</small></div><div class="card"><span>🪨</span><b>${kana}</b><small>Stones · kana</small></div></div><blockquote>“The more you learn, the more your garden grows.”</blockquote>`}

function companionView(){const s=getState(),comp=activeCompanion();return `<div><div class="eyebrow">Your learning companion</div><h1 class="page-title">Sakura</h1><p class="subtitle">Encouragement, progress and a little company for the road ahead.</p></div><section class="companion-profile section"><div class="companion-portrait"><img src="./assets/sakura-companion.webp" alt="Sakura waving"><div class="level-badge">Lv. ${level()}<small>${s.xp%100}/100 XP</small></div></div><div class="companion-message"><span>こんにちは！</span><h2>I’m Sakura.</h2><p>You’ve studied on <b>${s.studyDays.length} days</b> and grown <b>${masteredCount()} blossoms</b>. I’ll celebrate your progress, help you recover from mistakes and keep each journey focused.</p><div class="companion-effect"><b>Equipped effect</b><span>${comp.icon} ${comp.name} · ${comp.effect}</span></div></div></section><section class="section"><div class="section-head"><h2>Companion styles</h2><span>Earned through learning</span></div><div class="style-row"><button class="style-card active"><span>🌸</span><b>Default</b><small>Always available</small></button><button class="style-card ${Object.keys(s.grammar).length>=4?'':'locked'}"><span>📚</span><b>Scholar</b><small>${Object.keys(s.grammar).length>=4?'Earned':'Learn 4 grammar'}</small></button><button class="style-card ${s.studyDays.length>=7?'':'locked'}"><span>☕</span><b>Casual</b><small>${s.studyDays.length>=7?'Earned':'Study 7 days'}</small></button><button class="style-card ${masteredCount()>=10?'':'locked'}"><span>👘</span><b>Festival</b><small>${masteredCount()>=10?'Earned':'Master 10 words'}</small></button></div></section><div class="profile-actions section"><button class="btn btn-ghost" data-go="settings">⚙ Settings & backup</button><button class="btn btn-ghost" data-go="studio">◇ Content Studio</button></div>`}

function statsView(){const s=getState(),answers=s.answers,correct=answers.filter(a=>a.correct).length,acc=answers.length?Math.round(correct/answers.length*100):0,mastered=Object.values(s.reviews).filter(r=>mastery(r)>=4).length;const cats=[...new Set(vocabulary.map(w=>w.category))].map(c=>{const ids=vocabulary.filter(w=>w.category===c).map(w=>w.id),a=answers.filter(x=>x.kind==='word'&&ids.includes(x.id));return {c,p:a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):0,n:a.length}}).sort((a,b)=>b.p-a.p);return `<div><div class="eyebrow">Learning record</div><h1 class="page-title">Statistics</h1><p class="subtitle">See what is sticking and where to focus next.</p></div><div class="grid stats-grid section"><div class="card"><div class="big-number">${acc}%</div><div class="metric-label">Overall accuracy</div></div><div class="card"><div class="big-number">${mastered}</div><div class="metric-label">Words mastered</div></div><div class="card"><div class="big-number">${Object.keys(s.kana).length}</div><div class="metric-label">Kana practised</div></div><div class="card"><div class="big-number">${s.studyDays.length}</div><div class="metric-label">Study days</div></div></div><div class="grid grid-2 section"><div class="card"><h3>Accuracy by category</h3>${cats.map(x=>`<div class="category-row"><span>${x.c}</span><div class="bar"><span style="width:${x.p}%;background:${x.n? 'var(--blue)':'#dfe3e6'}"></span></div><b>${x.n?x.p+'%':'—'}</b></div>`).join('')}</div><div class="card"><h3>Strongest & weakest</h3><p style="margin:12px 0"><b>Strongest:</b> ${cats.find(x=>x.n)?.c||'Complete a lesson first'}</p><p><b>Needs practice:</b> ${[...cats].reverse().find(x=>x.n)?.c||'No mistakes recorded yet'}</p><h3 style="margin-top:22px">Recent accuracy</h3>${weekBars(answers)}</div></div><section class="section"><div class="section-head"><h2>Achievements</h2><span>Learning milestones</span></div><div class="achievement-grid">${achievementData.map(a=>`<div class="card achievement ${s.achievements.includes(a.id)?'':'locked'}"><span class="achievement-icon">${a.icon}</span><div><h3>${a.name}</h3><p>${a.detail}</p></div></div>`).join('')}</div></section>`}
function weekBars(answers){return `<div style="display:flex;gap:8px;align-items:end;height:100px;margin-top:14px">${[6,5,4,3,2,1,0].map(d=>{const day=new Date(Date.now()-d*86400000).toISOString().slice(0,10),a=answers.filter(x=>x.date.startsWith(day)),p=a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):4;return `<div style="flex:1;text-align:center"><div style="height:${p}px;background:${a.length?'var(--blue)':'#e8ebed'};border-radius:5px 5px 2px 2px"></div><small>${new Date(day).toLocaleDateString(undefined,{weekday:'narrow'})}</small></div>`}).join('')}</div>`}

function studioView(){const report=validateContent(),sample=`{\n  "id": "word.unique-id",\n  "kana": "...",\n  "kanji": "...",\n  "romaji": "...",\n  "meaning": "...",\n  "category": "...",\n  "difficulty": 1,\n  "area": "sakura",\n  "example": "...",\n  "exampleEn": "..."\n}`;return `<div><div class="eyebrow">Curriculum workshop</div><h1 class="page-title">Content Studio</h1><p class="subtitle">Inspect the learning graph and validate content before it becomes part of the game.</p></div><div class="grid grid-2 section"><section class="card"><div class="validation-head"><span class="validation-mark ${report.valid?'valid':'invalid'}">${report.valid?'✓':'!'}</span><div><h3>${report.valid?'Content is ready':'Content needs attention'}</h3><p>${report.issues.length?`${report.issues.length} issues found`:'All stable IDs, references and required learning fields passed.'}</p></div></div><div class="content-counts">${Object.entries(report.counts).map(([k,v])=>`<div><b>${v}</b><span>${k}</span></div>`).join('')}</div>${report.issues.map(i=>`<div class="issue"><b>${i.where}</b> ${i.message}</div>`).join('')}</section><section class="card"><h3>Add a vocabulary record</h3><p>Copy this schema into the curriculum data file. Validation catches missing fields, duplicate IDs and broken references.</p><pre class="schema-code">${esc(sample)}</pre><button class="btn btn-secondary btn-small" id="copySchema">Copy schema</button></section></div><section class="card section"><div class="section-head"><h2>Prerequisite graph</h2><span>Schema v${contentManifest.schemaVersion}</span></div><div class="manifest-list">${curriculum.map(n=>`<div><b>${n.id}</b><span>${n.type}</span><small>${n.requires.length?n.requires.join(' → '):'entry point'}</small></div>`).join('')}</div></section>`}

function settingsView(){const s=getState();return `<div><div class="eyebrow">Make it yours</div><h1 class="page-title">Settings & backup</h1><p class="subtitle">Choose how Japanese appears and protect your learning history.</p></div><div class="grid settings-grid section"><section class="card"><h3>Learning display</h3>${toggleSetting('romaji','Show romaji','Latin reading beneath Japanese')}${toggleSetting('furigana','Show kanji forms','Display kanji beneath kana')}${toggleSetting('sound','Sound & pronunciation','Allow speech playback')}${toggleSetting('reducedMotion','Reduced animation','Remove movement and transitions')}<div class="setting-row"><div><b>Text size</b><small>Interface font size</small></div><select class="input" data-setting="fontSize"><option value="16" ${s.settings.fontSize==16?'selected':''}>Standard</option><option value="18" ${s.settings.fontSize==18?'selected':''}>Large</option><option value="20" ${s.settings.fontSize==20?'selected':''}>Extra large</option></select></div><div class="setting-row"><div><b>Journey length</b><small>Steps in a generated session</small></div><select class="input" data-setting="sessionLength"><option value="5" ${s.settings.sessionLength==5?'selected':''}>5 steps</option><option value="7" ${s.settings.sessionLength==7?'selected':''}>7 steps</option><option value="10" ${s.settings.sessionLength==10?'selected':''}>10 steps</option></select></div></section><section class="card"><h3>Companions</h3><p>Each companion gives a small learning effect.</p>${companions.map(c=>`<div class="setting-row"><div><b>${c.icon} ${c.name}</b><small>${c.effect}</small></div><button class="btn btn-small ${s.companion===c.id?'btn-primary':'btn-ghost'}" data-companion="${c.id}" ${s.xp<c.unlock?'disabled':''}>${s.xp<c.unlock?`${c.unlock} XP`:s.companion===c.id?'Equipped':'Equip'}</button></div>`).join('')}</section></div><section class="card section"><h3>Save backup</h3><p>Export a copy before moving browsers or devices. Importing replaces the progress currently stored here.</p><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:15px"><button class="btn btn-secondary" id="exportSave">↓ Export save</button><label class="btn btn-ghost">↑ Import save<input id="importSave" type="file" accept="application/json" hidden></label><button class="btn btn-danger" id="resetSave">Reset progress</button></div></section>`}
function toggleSetting(id,title,detail){return `<label class="setting-row"><div><b>${title}</b><small>${detail}</small></div><input type="checkbox" data-setting="${id}" ${getState().settings[id]?'checked':''}></label>`}

function startSession(kind,items,title,nodeId=null){if(!items.length){toast('Nothing is due yet — try a lesson instead.');return}session={kind,title,nodeId,items:items.map(makeQuestion),index:0,score:0,answered:false,protected:false};render()}
function makeQuestion(item){if(item.type==='kana'){const pool=kanaFamilies.flatMap(f=>f.items).filter(x=>x[1]!==item.romaji);return {...item,stage:'recognition',options:shuffle([item.romaji,...shuffle(pool).slice(0,3).map(x=>x[1])])}}const w=item.word,stage=item.stage||'recognition',others=shuffle(vocabulary.filter(x=>x.id!==w.id)).slice(0,3);if(stage==='listening')return {...item,stage,prompt:'♪',sub:'Listen, then choose the meaning',answer:w.meaning,options:shuffle([w.meaning,...others.map(x=>x.meaning)])};if(stage==='recall')return {...item,stage,prompt:w.meaning,sub:'Type the Japanese reading',answer:w.kana};if(stage==='production')return {...item,stage,prompt:w.exampleEn,sub:'Type the missing Japanese word',answer:w.kana};const byMeaning=Math.random()>.5;return {...item,stage,prompt:byMeaning?w.kana:w.meaning,sub:byMeaning?'Choose the meaning':'Choose the Japanese',answer:byMeaning?w.meaning:w.kana,options:shuffle([byMeaning?w.meaning:w.kana,...others.map(x=>byMeaning?x.meaning:x.kana)])}}
function renderSession(){const q=session.items[session.index],pct=session.index/session.items.length*100;if(session.done)return `<div class="session-wrap"><div class="reward-card"><img src="./assets/sakura-celebration.webp" alt="Sakura celebrating your lesson"><div class="reward-copy"><div class="eyebrow">Lesson complete</div><h1>Beautiful work!</h1><p>You answered ${session.score} of ${session.items.length} correctly and helped your garden grow.</p><div class="reward-list"><span>🔥 <b>+${session.score*12}</b> learning XP</span><span>✿ <b>${Math.round(session.score/session.items.length*100)}%</b> accuracy</span><span>文 <b>${dueWords().length}</b> reviews remain</span></div><blockquote>“Every little step leads to something amazing.”</blockquote><button class="btn btn-primary" id="finishSession">Continue the path →</button></div></div></div>`;const typed=q.type==='word'&&(q.stage==='recall'||q.stage==='production');return `<div class="session-wrap"><div class="session-head"><button class="btn btn-ghost btn-small" id="exitSession">← Exit</button><div class="progress"><span style="width:${pct}%"></span></div><b>${session.index+1}/${session.items.length}</b></div><div class="card quiz-card"><div class="quiz-type">${session.title} · ${q.type==='kana'?'Kana recall':stageLabel(q.stage)}</div>${q.stage==='listening'?`<button class="listen-button" data-speak="${q.word.kana}" aria-label="Play Japanese audio">♪</button>`:`<button class="btn btn-ghost btn-small" style="margin-top:15px" data-speak="${q.type==='kana'?q.char:q.word.kana}">♪ Hear it</button>`}<div class="prompt-jp ${q.stage==='production'?'sentence-prompt':''}">${esc(q.type==='kana'?q.char:q.prompt)}</div>${q.type==='word'&&q.stage==='recognition'&&getState().settings.romaji?`<div class="prompt-romaji">${q.prompt===q.word.kana?q.word.romaji:''}</div>`:''}<div class="prompt-label">${q.type==='kana'?'Choose the romaji':q.sub}</div>${typed?`<form class="type-answer" id="sessionForm"><input class="input" id="sessionInput" lang="ja" autocomplete="off" placeholder="Type in Japanese…"><button class="btn btn-primary">Check</button></form>`:`<div class="answers">${q.options.map(o=>`<button class="answer" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`}<div class="feedback" id="feedback"></div><div class="session-actions"><button class="btn btn-primary" id="nextQuestion" hidden>${session.index===session.items.length-1?'See results':'Continue →'}</button></div></div></div>`}
function answerQuestion(value,button){if(session.answered)return;const q=session.items[session.index],correct=q.type==='kana'?q.romaji:q.answer,norm=x=>String(x).replace(/[。、.!！?？\s]/g,'').toLowerCase(),ok=norm(value)===norm(correct)||(q.type==='word'&&norm(value)===norm(q.word.romaji));session.answered=true;if(ok)session.score++;else if(activeCompanion().id==='kitsune'&&!session.protected){session.protected=true;toast('Kiko protected your combo.')}if(q.type==='kana')recordKana(q.char,ok);else recordWord(q.word.id,ok,q.stage);document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;if(b.dataset.answer===correct)b.classList.add('correct')});if(!ok&&button)button.classList.add('wrong');const feedback=document.querySelector('#feedback');feedback.textContent=ok?'Correct! よくできました。':`Almost — the answer is ${correct}.`;feedback.style.color=ok?'var(--green)':'#a13232';document.querySelector('#nextQuestion').hidden=false}

function bindView(){document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{const k=b.dataset.start;if(k==='journey')startSession(k,journeyItems(),"Today's Journey");if(k==='review')startSession(k,dueWords().slice(0,getState().settings.sessionLength).map(word=>({type:'word',word,stage:nextSkill(getState().reviews[word.id])})),'Smart Review');if(k==='mistakes')startSession(k,mistakeItems(),'Mistake Practice');if(k==='kana'){const f=kanaFamilies[Math.min(kanaFamilies.length-1,Math.floor(getState().xp/100))];startSession(k,f.items.map(([char,romaji])=>({type:'kana',char,romaji})),'Kana Training')}});
 document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{const ids=areas.flatMap(a=>a.groups).find(g=>g.id===b.dataset.group).words;startSession('lesson',ids.map(id=>({type:'word',word:vocabulary.find(w=>w.id===id)})),b.textContent.trim())});
 document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{const f=kanaFamilies.find(x=>x.id===b.dataset.family);startSession('kana',f.items.map(([char,romaji])=>({type:'kana',char,romaji})),f.name)});
 document.querySelectorAll('[data-grammar]').forEach(b=>b.onclick=()=>{completeGrammar(b.dataset.grammar);toast('Added to your Grammar Journal.');render()});
 document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>startConversation(b.dataset.scenario));
 document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>openNode(b.dataset.node));
 const tt=document.querySelector('#typingToggle');if(tt)tt.onchange=()=>conversationTyping=tt.checked;
 document.querySelectorAll('[data-journal]').forEach(b=>b.onclick=()=>{journalType=b.dataset.journal;render()});const search=document.querySelector('#journalSearch');if(search)search.oninput=()=>document.querySelectorAll('[data-search]').forEach(x=>x.style.display=x.dataset.search.includes(search.value.toLowerCase())?'':'none');
 bindSpeak();document.querySelectorAll('[data-setting]').forEach(el=>el.onchange=()=>{const key=el.dataset.setting,val=el.type==='checkbox'?el.checked:Number(el.value);update(s=>s.settings[key]=val);render()});document.querySelectorAll('[data-companion]').forEach(b=>b.onclick=()=>{update(s=>s.companion=b.dataset.companion);toast('Companion equipped.');render()});document.querySelector('#copySchema')?.addEventListener('click',async()=>{await navigator.clipboard.writeText('{"id":"word.unique-id","kana":"","kanji":"","romaji":"","meaning":"","category":"","difficulty":1,"area":"sakura","example":"","exampleEn":""}');toast('Vocabulary schema copied.')});bindBackup()}
function bindSession(){document.querySelector('#finishSession')?.addEventListener('click',()=>{if(session.nodeId)completeNode(session.nodeId);session=null;view='learn';render()});document.querySelector('#exitSession')?.addEventListener('click',()=>{session=null;render()});document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answerQuestion(b.dataset.answer,b));document.querySelector('#sessionForm')?.addEventListener('submit',e=>{e.preventDefault();answerQuestion(document.querySelector('#sessionInput').value,null)});document.querySelector('#nextQuestion')?.addEventListener('click',()=>{session.index++;session.answered=false;if(session.index>=session.items.length)session.done=true;render()});bindSpeak();const q=session.items?.[session.index];if(q?.stage==='listening')setTimeout(()=>speak(q.word.kana),250)}
function bindSpeak(){document.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak))}
function speak(text){if(!getState().settings.sound){toast('Sound is turned off in Settings.');return}if(!('speechSynthesis'in window)){toast('Speech is unavailable in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.82;speechSynthesis.speak(u)}

function openNode(id){const n=curriculum.find(x=>x.id===id);if(!n||(!nodeUnlocked(n)&&!nodeComplete(n)))return;if(n.type==='vocabulary'){const items=n.content.map(id=>{const word=vocabulary.find(w=>w.id===id);return {type:'word',word,stage:getState().reviews[id]?['recognition','listening','recall','production'][Math.min(3,mastery(getState().reviews[id]))]:'recognition'}});startSession('curriculum',items,n.title,n.id)}else if(n.type==='kana'){const f=kanaFamilies.find(x=>x.id===n.content[0]);startSession('curriculum',f.items.map(([char,romaji])=>({type:'kana',char,romaji})),n.title,n.id)}else if(n.type==='grammar'){n.content.forEach(completeGrammar);completeNode(n.id);toast('Grammar patterns added to your journal.');render()}else if(n.type==='story')startConversation(n.content[0],n.id)}
function startConversation(id,nodeId=null){const sc=scenarios.find(x=>x.id===id);session={conversation:true,sc,nodeId,sceneIndex:0,perfect:true,answered:false};app.innerHTML=shell(renderConversation());bindShell();bindConversation()}
function renderConversation(){const {sc}=session,scenes=sc.scenes||[sc],scene=scenes[session.sceneIndex];if(session.done)return `<div class="session-wrap"><div class="card quiz-card"><div class="action-icon">💬</div><h1 class="page-title">Story chapter complete</h1><p class="subtitle">You handled ${scenes.length} exchanges with ${sc.npc}${session.perfect?' without a mistake':''}.</p><div class="pattern" style="font-size:1rem;margin:28px 0"><b>${scene.model}</b><br>${scene.translation}</div><button class="btn btn-primary" id="finishConversation">Continue the story</button></div></div>`;return `<div class="session-wrap"><div class="session-head"><button class="btn btn-ghost btn-small" id="exitSession">× Exit</button><div class="progress"><span style="width:${session.sceneIndex/scenes.length*100}%"></span></div><b>${session.sceneIndex+1}/${scenes.length}</b></div><div class="card quiz-card"><div class="quiz-type">${sc.icon} ${sc.place} · Conversation with ${sc.npc}</div><div class="prompt-jp" style="font-size:2.4rem">${scene.prompt}</div><div class="prompt-label">${scene.translation}</div>${conversationTyping?`<form id="conversationForm" class="type-answer"><input class="input" id="conversationInput" lang="ja" autocomplete="off" placeholder="Type your answer in Japanese…"><button class="btn btn-primary">Reply</button></form>`:`<div class="answers">${shuffle(scene.answers).map(a=>`<button class="answer" data-reply="${a}">${a}</button>`).join('')}</div>`}<div class="feedback" id="feedback"></div><div class="session-actions"><button class="btn btn-primary" id="continueConversation" hidden>${session.sceneIndex===scenes.length-1?'Finish chapter →':'Next exchange →'}</button></div></div></div>`}
function bindConversation(){document.querySelector('#finishConversation')?.addEventListener('click',()=>{if(session.nodeId)completeNode(session.nodeId);session=null;view='learn';render()});document.querySelector('#exitSession')?.addEventListener('click',()=>{session=null;render()});const scenes=session.sc.scenes||[session.sc],scene=scenes[session.sceneIndex];const submit=value=>{if(session.answered)return;const normalized=value.replace(/[。、.!！?？\s]/g,''),ok=scene.answers.some(a=>normalized.includes(a.replace(/[。、.!！?？\s]/g,'')));session.answered=true;session.perfect=session.perfect&&ok;completeConversation(session.sc.id,ok);const f=document.querySelector('#feedback');f.innerHTML=ok?'自然です！ Great answer.':`Good attempt. A natural reply is <b>${scene.model}</b>`;f.style.color=ok?'var(--green)':'#a56a15';document.querySelector('#continueConversation').hidden=false};document.querySelector('#conversationForm')?.addEventListener('submit',e=>{e.preventDefault();submit(document.querySelector('#conversationInput').value)});document.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>submit(b.dataset.reply));document.querySelector('#continueConversation')?.addEventListener('click',()=>{session.sceneIndex++;session.answered=false;if(session.sceneIndex>=scenes.length){session.sceneIndex=scenes.length-1;session.done=true}app.innerHTML=shell(renderConversation());bindShell();bindConversation()})}
function bindBackup(){document.querySelector('#exportSave')?.addEventListener('click',()=>{const blob=new Blob([exportSave()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nihongo-quest-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Save exported.')});document.querySelector('#importSave')?.addEventListener('change',async e=>{try{importSave(await e.target.files[0].text());toast('Progress restored.');render()}catch(err){toast(err.message)}});document.querySelector('#resetSave')?.addEventListener('click',()=>{if(confirm('Reset all learning progress on this device?')){resetSave();toast('Progress reset.');render()}})}

update(()=>{});render();
