export const CULTURAL_CATEGORIES=['seasonal','home','traditional-craft','everyday-life','games','clothing'];
export const culturalItems=[
 {id:'furin',japanese:'風鈴',reading:'ふうりん',romaji:'fūrin',english:'Wind chime',category:'seasonal',summary:'A Japanese wind chime strongly associated with summer.',culturalNote:'Fūrin are often hung near windows or eaves; their sound is commonly linked with a cooling summer atmosphere.',discoveryId:'discovery.furin',audioId:'culture:furin',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.words.greetings'},purchasable:true,cost:null,placement:{type:'hanging',roomZone:'window'},season:'summer'},
 {id:'daruma',japanese:'だるま',reading:'だるま',romaji:'daruma',english:'Daruma doll',category:'everyday-life',summary:'A rounded figure used as a reminder of a goal.',culturalNote:'Daruma are commonly associated with setting a goal and perseverance; practices vary by person and region.',discoveryId:'discovery.daruma',audioId:'culture:daruma',image:{card:null,detail:null},unlock:{type:'milestone',value:'master10'},purchasable:true,cost:null,placement:{type:'shelf',roomZone:'shelf'},season:'year-round'},
 {id:'maneki-neko',japanese:'招き猫',reading:'まねきねこ',romaji:'maneki-neko',english:'Beckoning cat',category:'everyday-life',summary:'A figurine often displayed as a welcoming or lucky symbol.',culturalNote:'Maneki-neko are frequently seen in shops and homes, with different colours and raised paws carrying different associations.',discoveryId:'discovery.maneki-neko',audioId:'culture:maneki-neko',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.words.people'},purchasable:true,cost:null,placement:{type:'shelf',roomZone:'shelf'},season:'year-round'},
 {id:'omamori',japanese:'お守り',reading:'おまもり',romaji:'omamori',english:'Protective charm',category:'everyday-life',summary:'A small charm associated with a particular hope or protection.',culturalNote:'Omamori are commonly obtained at shrines or temples and are associated with purposes such as travel, study, or health.',discoveryId:'discovery.omamori',audioId:'culture:omamori',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.grammar.identity'},purchasable:true,cost:null,placement:{type:'shelf',roomZone:'desk'},season:'year-round'},
 {id:'sensu',japanese:'扇子',reading:'せんす',romaji:'sensu',english:'Folding fan',category:'clothing',summary:'A folding fan used for air, performance, or decoration.',culturalNote:'Sensu appear in everyday and artistic contexts; the material, design, and use depend on the setting.',discoveryId:'discovery.sensu',audioId:'culture:sensu',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.words.food'},purchasable:true,cost:null,placement:{type:'shelf',roomZone:'shelf'},season:'summer'},
 {id:'chochin',japanese:'提灯',reading:'ちょうちん',romaji:'chōchin',english:'Paper lantern',category:'seasonal',summary:'A collapsible lantern often seen at festivals and entrances.',culturalNote:'Chōchin can mark a shop, food stall, festival space, or ceremonial setting; they are not limited to one occasion.',discoveryId:'discovery.chochin',audioId:'culture:chochin',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.grammar.objects'},purchasable:true,cost:null,placement:{type:'hanging',roomZone:'entrance'},season:'summer'},
 {id:'kendama',japanese:'けん玉',reading:'けんだま',romaji:'kendama',english:'Kendama',category:'games',summary:'A skill toy played by catching a ball on cups or a spike.',culturalNote:'Kendama is played casually and competitively, with practice focused on coordination and control.',discoveryId:'discovery.kendama',audioId:'culture:kendama',image:{card:null,detail:null},unlock:{type:'milestone',value:'kana50'},purchasable:true,cost:null,placement:{type:'floor',roomZone:'play'},season:'year-round'},
 {id:'kokeshi',japanese:'こけし',reading:'こけし',romaji:'kokeshi',english:'Kokeshi doll',category:'traditional-craft',summary:'A simple wooden doll associated with craft traditions in northern Japan.',culturalNote:'Kokeshi styles vary by region and maker; the form is best understood as a family of wooden craft traditions.',discoveryId:'discovery.kokeshi',audioId:'culture:kokeshi',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.story.intro'},purchasable:true,cost:null,placement:{type:'shelf',roomZone:'shelf'},season:'year-round'},
 {id:'ema',japanese:'絵馬',reading:'えま',romaji:'ema',english:'Votive tablet',category:'everyday-life',summary:'A wooden tablet on which people may write a wish or thanks.',culturalNote:'Ema are commonly found at shrines; designs and customs differ, and people write a range of personal hopes.',discoveryId:'discovery.ema',audioId:'culture:ema',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.story.restaurant'},purchasable:true,cost:null,placement:{type:'wall',roomZone:'wall'},season:'year-round'},
 {id:'furoshiki',japanese:'風呂敷',reading:'ふろしき',romaji:'furoshiki',english:'Wrapping cloth',category:'everyday-life',summary:'A square cloth used for wrapping and carrying items.',culturalNote:'Furoshiki can be folded in different ways for different objects and are also used as reusable gift wrapping.',discoveryId:'discovery.furoshiki',audioId:'culture:furoshiki',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.words.food'},purchasable:true,cost:null,placement:{type:'tabletop',roomZone:'table'},season:'year-round'},
 {id:'chawan',japanese:'茶碗',reading:'ちゃわん',romaji:'chawan',english:'Rice bowl',category:'home',summary:'A bowl commonly used for rice or tea depending on context.',culturalNote:'Chawan means bowl, and its exact use depends on context; tableware styles vary between homes and regions.',discoveryId:'discovery.chawan',audioId:'culture:chawan',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.words.food'},purchasable:true,cost:null,placement:{type:'tabletop',roomZone:'table'},season:'year-round'},
 {id:'zabuton',japanese:'座布団',reading:'ざぶとん',romaji:'zabuton',english:'Floor cushion',category:'home',summary:'A cushion used for sitting on a floor or tatami surface.',culturalNote:'Zabuton are common in settings where people sit on the floor; their shape and use are practical as well as familiar.',discoveryId:'discovery.zabuton',audioId:'culture:zabuton',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.story.intro'},purchasable:true,cost:null,placement:{type:'floor',roomZone:'sitting'},season:'year-round'},
 {id:'noren',japanese:'暖簾',reading:'のれん',romaji:'noren',english:'Shop curtain',category:'home',summary:'A split fabric curtain used at entrances and as a visual sign.',culturalNote:'Noren are often seen at restaurants, shops, baths, and homes; the printed design can identify a place or family.',discoveryId:'discovery.noren',audioId:'culture:noren',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.story.restaurant'},purchasable:true,cost:null,placement:{type:'hanging',roomZone:'entrance'},season:'year-round'},
 {id:'geta',japanese:'下駄',reading:'げた',romaji:'geta',english:'Wooden sandals',category:'clothing',summary:'Traditional raised wooden footwear worn in some settings.',culturalNote:'Geta are associated with particular clothing and occasions, including some summer festivals; they are not everyday footwear for everyone.',discoveryId:'discovery.geta',audioId:'culture:geta',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.words.travel'},purchasable:true,cost:null,placement:{type:'floor',roomZone:'entrance'},season:'summer'},
 {id:'wagasa',japanese:'和傘',reading:'わがさ',romaji:'wagasa',english:'Japanese-style umbrella',category:'traditional-craft',summary:'A paper-and-bamboo umbrella made in Japanese craft traditions.',culturalNote:'Wagasa describes several styles of traditional umbrella, used in practical, ceremonial, and performance contexts.',discoveryId:'discovery.wagasa',audioId:'culture:wagasa',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.words.travel'},purchasable:true,cost:null,placement:{type:'floor',roomZone:'entrance'},season:'rainy-season'},
 {id:'konbini-bag',japanese:'レジ袋',reading:'れじぶくろ',romaji:'reji bukuro',english:'Checkout bag',category:'everyday-life',summary:'A bag provided at a checkout, now part of conversations about reuse and waste.',culturalNote:'The phrase is useful everyday vocabulary; access, charges, and reuse practices vary by shop and circumstance.',discoveryId:'discovery.konbini-bag',audioId:'culture:konbini-bag',image:{card:null,detail:null},unlock:{type:'curriculum',value:'path.words.people'},purchasable:true,cost:null,placement:{type:'shelf',roomZone:'counter'},season:'year-round'}
];
export const culturalById=new Map(culturalItems.map(item=>[item.id,item]));
export function getCulturalItem(id){return culturalById.get(id)||null}
export function validateCulturalItems(){const issues=[],ids=new Set(),discoveries=new Set(),audio=new Set();for(const item of culturalItems){if(ids.has(item.id))issues.push(`duplicate id: ${item.id}`);ids.add(item.id);if(!item.japanese||!item.reading||!item.english)issues.push(`missing name fields: ${item.id}`);if(!CULTURAL_CATEGORIES.includes(item.category))issues.push(`invalid category: ${item.id}`);if(discoveries.has(item.discoveryId))issues.push(`duplicate discovery: ${item.discoveryId}`);discoveries.add(item.discoveryId);if(!/^culture:[\w-]+$/.test(item.audioId)||audio.has(item.audioId))issues.push(`invalid audio id: ${item.id}`);audio.add(item.audioId);if(!item.placement?.type||!item.placement?.roomZone)issues.push(`missing placement: ${item.id}`)}return {valid:!issues.length,issues,counts:{items:culturalItems.length,images:culturalItems.filter(x=>x.image.card).length,audio:culturalItems.filter(x=>x.audioId).length,placement:culturalItems.filter(x=>x.placement).length,discoveryHooks:culturalItems.filter(x=>x.unlock).length}}}
