import {vocabulary,kanaFamilies,grammar,companions,confusionPairs,curriculum} from './data.js';
import {getState,update} from './state.js';
import {emitCompanion,COMPANION_EVENTS} from './companion.js';
const DAY=86400000;
export const shuffle=a=>[...a].sort(()=>Math.random()-.5);
export const SKILLS=['recognition','recall','listening','production'];
export const QUESTION_TYPES={WORD:'word',KANA:'kana'};
export const normalizeAnswer=value=>String(value??'').normalize('NFKC').replace(/[。、.!！?？\s]/g,'').toLowerCase();
export function createQuestion(item,{source='practice'}={}){
 if(!item||!item.type)throw new TypeError('A question item must include a content type.');
 if(item.type==='kana')return {id:`kana:${item.char}`,contentId:item.char,contentType:'kana',stage:item.stage||'recognition',prompt:item.char,expected:item.romaji,accepted:[],inputType:'choice',choices:item.options||[],audioTarget:item.char,source,metadata:{romaji:item.romaji}};
 const word=item.word;if(!word?.id||!word.kana)throw new TypeError('A vocabulary question requires a word id and kana.');const stage=item.stage||'recognition';
 const prompt=item.prompt??(stage==='recall'?word.meaning:stage==='production'?word.exampleEn:word.kana);
 const expected=item.answer|| (stage==='recall'||stage==='production'?word.kana:word.meaning);
 const japaneseAnswer=expected===word.kana||stage==='recall'||stage==='production';
 return {id:`${word.id}:${stage}`,contentId:word.id,contentType:'word',stage,prompt,expected,accepted:item.accepted||(japaneseAnswer?[word.romaji]:[]),inputType:item.inputType||(stage==='recall'||stage==='production'?'text':'choice'),choices:item.options||[],audioTarget:word.kana,source,metadata:{word}};
}
export function evaluateAnswer(question,submitted){const value=String(submitted??''),expected=String(question.expected??''),accepted=[expected,...(question.accepted||[])].filter(Boolean);const matched=accepted.find(answer=>normalizeAnswer(answer)===normalizeAnswer(value));return {correct:Boolean(matched),submitted:value,expected,matchedAlternative:matched&&matched!==expected?matched:null,contentId:question.contentId,contentType:question.contentType,stage:question.stage,source:question.source,questionId:question.id};}
export function evaluateConversationAnswer({scenarioId,sceneIndex,answers,model},submitted){const value=String(submitted??''),matched=(answers||[]).find(answer=>normalizeAnswer(answer)===normalizeAnswer(value));return {correct:Boolean(matched),submitted:value,expected:answers?.[0]||'',matchedAlternative:matched&&matched!==answers?.[0]?matched:null,contentId:scenarioId,contentType:'conversation',stage:'conversation',source:'scenario',questionId:`${scenarioId}:${sceneIndex}`,model};}
export const skillScores=r=>({recognition:0,recall:0,listening:0,production:0,...r?.skills});
export const mastery=r=>!r?0:Math.min(5,Math.floor(Object.values(skillScores(r)).reduce((a,b)=>a+b,0)/80));
export const overallMastery=r=>Math.round(Object.values(skillScores(r)).reduce((a,b)=>a+b,0)/4);
export const GARDEN_LEVELS=[{name:'Seed',threshold:0},{name:'Sprout',threshold:8},{name:'Young Tree',threshold:22},{name:'First Bloom',threshold:42},{name:'Flourishing',threshold:70},{name:'Moonlit Garden',threshold:105},{name:'Full Bloom',threshold:150}];
export const GARDEN_UNLOCKS=[
 {id:'first-blossom',label:'First blossom',description:'A mastered word takes root.',when:c=>c.blossoms>=1},
 {id:'stone-path',label:'Kana path',description:'Three strengthened kana become stepping stones.',when:c=>c.kana>=3},
 {id:'branch',label:'New branch',description:'A completed curriculum chapter grows the tree.',when:c=>c.branches>=1},
 {id:'lantern',label:'Grammar lantern',description:'A learned grammar structure lights the Garden.',when:c=>c.grammar>=1},
 {id:'songbird',label:'Garden songbird',description:'A completed conversation brings a little life.',when:c=>c.conversations>=1},
 {id:'moonlit',label:'Moonlit accents',description:'Reach Garden level 6.',when:(c,p)=>p.level>=6},
 {id:'pond',label:'Pond details',description:'Reach Garden level 7.',when:(c,p)=>p.level>=7}
];
export function gardenCounts(s=getState()){return {blossoms:vocabulary.filter(w=>mastery(s.reviews?.[w.id])>=4).length,kana:Object.values(s.kana||{}).filter(r=>(r.correct||0)>=3).length,grammar:grammar.filter(g=>s.grammar?.[g.id]?.learned).length,conversations:Object.keys(s.conversations||{}).filter(id=>scenariosForGarden.has(id)).length,branches:curriculum.filter(n=>s.curriculum?.[n.id]?.complete).length}}
const scenariosForGarden=new Set(['intro','school','restaurant','shop','station','directions','routine']);
export function gardenGrowthScore(counts){return counts.blossoms*4+counts.kana+counts.grammar*3+counts.conversations*4+counts.branches*5}
export function gardenProgress(s=getState()){const counts=gardenCounts(s),score=gardenGrowthScore(counts),index=Math.max(0,GARDEN_LEVELS.findLastIndex(level=>score>=level.threshold)),current=GARDEN_LEVELS[index],next=GARDEN_LEVELS[index+1]||null;return {counts,score,level:index+1,levelName:current.name,nextLevel:next?.name||null,nextThreshold:next?.threshold||score,progressToNext:next?Math.round((score-current.threshold)/(next.threshold-current.threshold)*100):100,unlocked:GARDEN_UNLOCKS.filter(item=>item.when(counts,{level:index+1,score})).map(item=>item.id)}}
function gardenGrowthMessages(changed){return Object.entries(changed).filter(([,amount])=>amount>0).map(([kind,amount])=>({blossoms:`🌸 ${amount} new ${amount===1?'blossom':'blossoms'} grew`,kana:`🪨 Your kana path grew`,grammar:`🏮 ${amount===1?'A grammar lantern was lit':`${amount} grammar lanterns were lit`}`,conversations:'🐦 Your Garden gained a songbird',branches:`🌿 ${amount===1?'A new branch appeared':`${amount} new branches appeared`}`}[kind])).filter(Boolean)}
export function syncGardenProgress({announce=true}={}){const s=getState(),current=gardenProgress(s),garden=s.garden||{},prior=garden.lastCounts||current.counts;if(!garden.initialized){update(x=>x.garden={...x.garden,initialized:true,lastCounts:current.counts,milestones:current.unlocked.map(id=>({id,date:Date.now()})),recentGrowth:[]});return current}const changed=Object.fromEntries(Object.keys(current.counts).map(key=>[key,Math.max(0,current.counts[key]-(prior[key]||0))]));const messages=gardenGrowthMessages(changed),newUnlocks=current.unlocked.filter(id=>!(garden.milestones||[]).some(m=>m.id===id)),levelBefore=Math.max(1,GARDEN_LEVELS.findLastIndex(level=>gardenGrowthScore(prior)>=level.threshold)+1),didGrow=messages.length>0||newUnlocks.length>0;update(x=>x.garden={...x.garden,lastCounts:current.counts,milestones:[...(x.garden?.milestones||[]),...newUnlocks.map(id=>({id,date:Date.now()}))].slice(-50),recentGrowth:didGrow?[...messages,...newUnlocks.map(id=>`✨ ${GARDEN_UNLOCKS.find(item=>item.id===id)?.label||'A new Garden detail'} unlocked`),...(x.garden?.recentGrowth||[])].slice(0,6):x.garden?.recentGrowth||[]});if(announce&&didGrow){if(current.level>levelBefore)emitCompanion(COMPANION_EVENTS.GARDEN_LEVEL_UP,{level:current.level});if(newUnlocks.length)emitCompanion(COMPANION_EVENTS.GARDEN_UNLOCK,{unlocks:newUnlocks});if(current.level===levelBefore&&!newUnlocks.length)emitCompanion(COMPANION_EVENTS.GARDEN_GROWTH,{growth:messages})}return current}
export const nextSkill=r=>[...SKILLS].sort((a,b)=>skillScores(r)[a]-skillScores(r)[b])[0];
export const dueWords=()=>vocabulary.filter(w=>{const r=getState().reviews[w.id];return !r||!r.due||r.due<=Date.now()}).sort((a,b)=>(getState().reviews[b.id]?.wrong||0)-(getState().reviews[a.id]?.wrong||0));
export const weakWords=()=>vocabulary.filter(w=>getState().reviews[w.id]?.wrong).sort((a,b)=>{const x=getState().reviews;return (x[b.id].wrong-x[b.id].correct)-(x[a.id].wrong-x[a.id].correct)});
export function recordWord(id,correct,mode='recognition',meta={}){
 const skill=SKILLS.includes(mode)?mode:(mode==='listening'?'listening':'recognition');
 update(s=>{const r=s.reviews[id]||{correct:0,wrong:0,interval:0,due:0,skills:{recognition:0,recall:0,listening:0,production:0}};r.skills=skillScores(r);r.skills[skill]=Math.max(0,Math.min(100,r.skills[skill]+(correct?18:-11)));if(correct){r.correct++;const floor=Math.min(...Object.values(r.skills));r.interval=floor<30?1:floor<60?3:Math.min(30,Math.max(7,Math.round((r.interval||3)*1.7)));r.due=Date.now()+r.interval*DAY;s.xp+=skill==='production'?18:12}else{r.wrong++;r.interval=0;r.due=Date.now()+10*60*1000}r.last=Date.now();s.reviews[id]=r;s.answers.push({date:new Date().toISOString(),kind:'word',id,correct,mode:skill});s.quests.review++;if(mastery(r)>=4)s.quests.master=Math.max(s.quests.master,Object.values(s.reviews).filter(x=>mastery(x)>=4).length);touchDay(s)});
 checkAchievements();emitCompanion(correct?COMPANION_EVENTS.ANSWER_CORRECT:COMPANION_EVENTS.ANSWER_INCORRECT,{wordId:id,...meta});syncGardenProgress({announce:true});
}
export function recordAnswerResult(result){
 if(result.attemptId&&getState().processedAttempts?.[result.attemptId])return {...result,duplicate:true};
 if(result.contentType==='kana')recordKana(result.contentId,result.correct,result);
 else recordWord(result.contentId,result.correct,result.stage,result);
 if(result.attemptId)update(s=>{s.processedAttempts={...(s.processedAttempts||{}),[result.attemptId]:Date.now()}});
 update(s=>{s.answerStreak=result.correct?(s.answerStreak||0)+1:0});
 if(result.correct&&getState().answerStreak>=3)emitCompanion(COMPANION_EVENTS.ANSWER_STREAK,{streak:getState().answerStreak,focus:result.focus});
 return result;
}
export function completeSession(summary={}){emitCompanion(COMPANION_EVENTS.SESSION_COMPLETED,{message:summary.message||'Session complete — your practice is safely recorded.'});return summary;}
export function recordKana(char,correct,meta={}){update(s=>{const r=s.kana[char]||{correct:0,wrong:0};r[correct?'correct':'wrong']++;s.kana[char]=r;s.answers.push({date:new Date().toISOString(),kind:'kana',id:char,correct});if(correct)s.xp+=8;touchDay(s)});checkAchievements();emitCompanion(correct?COMPANION_EVENTS.ANSWER_CORRECT:COMPANION_EVENTS.ANSWER_INCORRECT,{kana:char,...meta});syncGardenProgress({announce:true})}
export function completeGrammar(id){if(getState().grammar[id]?.learned)return {id,duplicate:true};update(s=>{s.grammar[id]={learned:true,date:Date.now()};s.xp+=20;touchDay(s)});checkAchievements();emitCompanion(COMPANION_EVENTS.LESSON_COMPLETE,{message:'That grammar pattern is now in your journal.'});syncGardenProgress({announce:true});return {id,duplicate:false}}
export function completeConversation(id,perfect){update(s=>{s.conversations[id]={count:(s.conversations[id]?.count||0)+1,perfect:perfect||s.conversations[id]?.perfect};s.quests.conversation++;s.xp+=perfect?30:20;touchDay(s)});checkAchievements();emitCompanion(COMPANION_EVENTS.LESSON_COMPLETE,{message:perfect?'A perfect conversation! Sakura is cheering for you.':'Conversation complete. Every reply helps.'});syncGardenProgress({announce:true})}
function touchDay(s){const d=new Date().toISOString().slice(0,10);if(!s.studyDays.includes(d))s.studyDays.push(d);s.lastStudy=d}
export function checkAchievements(){update(s=>{const add=(id)=>{if(!s.achievements.includes(id))s.achievements.push(id)};const kanaCorrect=s.answers.filter(a=>a.kind==='kana'&&a.correct).length;if(kanaCorrect>=50)add('kana50');if(Object.values(s.reviews).filter(r=>mastery(r)>=4).length>=10)add('master10');if(Object.values(s.conversations).some(c=>c.perfect))add('perfectTalk');if(s.studyDays.length>=7)add('week')})}
export const achievementData=[{id:'kana50',icon:'あ',name:'Kana Spark',detail:'50 kana correct'},{id:'master10',icon:'🏆',name:'Word Keeper',detail:'10 words mastered'},{id:'perfectTalk',icon:'💬',name:'Smooth Talker',detail:'Perfect conversation'},{id:'week',icon:'🔥',name:'Seven Suns',detail:'Study on 7 days'}];
export function journeyItems(){const s=getState(),n=s.settings.sessionLength;const due=dueWords(),weak=weakWords();const dueIds=new Set(due.map(w=>w.id)),weakIds=new Set(weak.map(w=>w.id));const words=[...new Map([...weak.slice(0,2),...due,...shuffle(vocabulary)].map(w=>[w.id,w])).values()].slice(0,Math.max(3,n-2));const unlockedFamilies=kanaFamilies.slice(0,Math.max(1,Math.floor(s.xp/100)+1));const fam=unlockedFamilies[unlockedFamilies.length-1];const kana=shuffle(fam.items).slice(0,2).map(([char,romaji])=>({type:'kana',char,romaji,source:'new material'}));return shuffle([...words.map(word=>({type:'word',word,stage:nextSkill(s.reviews[word.id]),source:weakIds.has(word.id)?'recent mistake':dueIds.has(word.id)?'due review':'new material'})),...kana]).slice(0,n)}
export function mistakeItems(){const weak=weakWords();const kana=Object.entries(getState().kana).filter(([,r])=>r.wrong>r.correct/2).sort((a,b)=>b[1].wrong-a[1].wrong).flatMap(([char])=>{for(const f of kanaFamilies){const x=f.items.find(i=>i[0]===char);if(x){const pair=confusionPairs.find(p=>p[0]===char||p[1]===char),paired=pair&&f.items.find(i=>i[0]===(pair[0]===char?pair[1]:pair[0]));return [{type:'kana',char,romaji:x[1],source:'recent mistake'},...(paired?[{type:'kana',char:paired[0],romaji:paired[1],source:'confusion pair'}]:[])]}}return []});return [...weak.slice(0,6).map(word=>({type:'word',word,source:'recent mistake'})),...kana.slice(0,4)]}
export function buildSession(mode,options={}){
 if(mode==='journey')return {mode,reason:'balanced journey',items:journeyItems()};
 if(mode==='review')return {mode,reason:'due review',items:dueWords().slice(0,options.length||getState().settings.sessionLength).map(word=>({type:'word',word,stage:nextSkill(getState().reviews[word.id]),source:'due review'}))};
 if(mode==='mistakes')return {mode,reason:'recent mistakes',items:mistakeItems()};
 if(mode==='focused')return {mode,reason:'focused practice',items:options.items||[]};
 if(mode==='curriculum')return {mode,reason:'curriculum requirement',items:options.items||[]};
 return {mode,reason:'practice',items:options.items||[]};
}
export const FOCUS_PROFILES={2:{duration:2,steps:3,label:'2-minute Focus Quest',prompt:'I just want to do something.'},5:{duration:5,steps:6,label:'5-minute Focus Quest',prompt:'A small focused session.'},10:{duration:10,steps:10,label:'10-minute Focus Quest',prompt:'A proper study session.'}};
export function buildFocusSession(duration=5){
 const profile=FOCUS_PROFILES[duration]||FOCUS_PROFILES[5],s=getState(),due=dueWords(),weak=weakWords(),seen=new Set(),items=[];
 const add=(item,source)=>{const id=item.type==='word'?item.word.id:`kana:${item.char}`;if(seen.has(id))return;seen.add(id);items.push({...item,source})};
 due.slice(0,profile.steps).forEach(word=>add({type:'word',word,stage:nextSkill(s.reviews[word.id])},'due review'));
 weak.slice(0,profile.steps).forEach(word=>add({type:'word',word,stage:nextSkill(s.reviews[word.id])},'recent mistake'));
 const family=kanaFamilies[Math.min(kanaFamilies.length-1,Math.floor(s.xp/100))];
 family.items.slice(0,2).forEach(([char,romaji])=>add({type:'kana',char,romaji},'focused reinforcement'));
 shuffle(vocabulary).forEach(word=>{if(items.length<profile.steps)add({type:'word',word,stage:'recognition'},'new material')});
 return {mode:'focus',duration:profile.duration,reason:'focused low-friction practice',budget:profile.steps,items:items.slice(0,profile.steps)};
}
export function focusResumeIndex(checkpoint,total){return Math.min((checkpoint?.index||0)+(checkpoint?.answered?1:0),Math.max(0,total-1))}
export function recordFocusSession(metadata){update(s=>{s.focus={...(s.focus||{}),lastDuration:metadata.duration,sessions:[...(s.focus?.sessions||[]),{...metadata,date:Date.now()}].slice(-20)}});return metadata}
export function describeSession(session){return (session?.items||[]).map(item=>({contentId:item.type==='word'?item.word?.id:item.char,contentType:item.type,stage:item.stage||'recognition',source:item.source||session.reason||'practice',mastery:item.type==='word'?mastery(getState().reviews[item.word.id]):null}));}
export function dailyQuests(){const s=getState();if(s.quests.date!==new Date().toISOString().slice(0,10))update(x=>x.quests={date:new Date().toISOString().slice(0,10),review:0,master:0,conversation:0});return [{label:'Review 10 items',value:s.quests.review,target:10,icon:'↻'},{label:'Master 2 words',value:s.quests.master,target:2,icon:'◆'},{label:'Complete a conversation',value:s.quests.conversation,target:1,icon:'💬'}]}
export const weeklyQuest=()=>({label:'Study on 5 days',value:getState().studyDays.filter(d=>Date.now()-new Date(d).getTime()<7*DAY).length,target:5});
export const currentGrammar=()=>grammar.filter(g=>g.level<=Math.max(1,Math.floor(getState().xp/160)+1));
export const activeCompanion=()=>({id:'sakura',name:'Sakura',icon:'🌸',effect:'Reacts to your learning events and keeps you moving.'});
export function confusionFor(char){return confusionPairs.find(p=>p[0]===char||p[1]===char)}
export const nodeUnlocked=node=>node.requires.every(id=>getState().curriculum[id]?.complete);
export const nodeComplete=id=>!!getState().curriculum[id]?.complete;
export function completeNode(id){if(nodeComplete(id))return;update(s=>{s.curriculum[id]={complete:true,date:Date.now()};s.xp+=25;touchDay(s)});checkAchievements();emitCompanion(COMPANION_EVENTS.NEW_MILESTONE,{nodeId:id,message:'A new chapter is open. That was a meaningful step.'});syncGardenProgress({announce:true})}
export function nextCurriculumNode(){return curriculum.find(n=>nodeUnlocked(n)&&!nodeComplete(n))||curriculum[curriculum.length-1]}
export function curriculumProgress(){return curriculum.filter(n=>nodeComplete(n)).length/curriculum.length}
export function stageLabel(stage){return {recognition:'Recognise',recall:'Recall from memory',listening:'Listen',production:'Produce Japanese'}[stage]}
export const JOURNEY_CHAPTERS=[
 {id:'first-sounds',title:'First Sounds',subtitle:'Meet the kana that open the journey.',nodeIds:['path.kana.vowels','path.words.greetings']},
 {id:'say-it-clearly',title:'Say It Clearly',subtitle:'Build your first sentences and introductions.',nodeIds:['path.grammar.identity','path.story.intro']},
 {id:'more-sounds',title:'More Sounds, More People',subtitle:'Extend the kana path and talk about people.',nodeIds:['path.kana.k','path.words.people']},
 {id:'everyday-japanese',title:'Everyday Japanese',subtitle:'Order simply and understand daily words.',nodeIds:['path.words.food','path.grammar.objects','path.story.restaurant']},
 {id:'finding-your-way',title:'Finding Your Way',subtitle:'Use Japanese around town.',nodeIds:['path.words.travel','path.grammar.destination','path.story.station']}
];
export function curriculumItems(node,s=getState()){if(!node)return[];if(node.type==='vocabulary')return node.content.map(id=>{const word=vocabulary.find(item=>item.id===id);return {type:'word',word,stage:s.reviews?.[id]?['recognition','listening','recall','production'][Math.min(3,mastery(s.reviews[id]))]:'recognition',source:'curriculum requirement'}});if(node.type==='kana'){const family=kanaFamilies.find(item=>item.id===node.content[0]);return family.items.map(([char,romaji])=>({type:'kana',char,romaji,source:'curriculum requirement'}))}return[]}
export function journeyNodeProgress(node,s=getState()){if(nodeComplete(node.id))return 100;if(node.type==='vocabulary')return Math.round(curriculumItems(node,s).filter(item=>mastery(s.reviews?.[item.word.id])>=4).length/node.content.length*100);if(node.type==='kana'){const items=curriculumItems(node,s);return Math.round(items.filter(item=>(s.kana?.[item.char]?.correct||0)>=3).length/items.length*100)}if(node.type==='grammar')return Math.round(node.content.filter(id=>s.grammar?.[id]?.learned).length/node.content.length*100);if(node.type==='story')return s.conversations?.[node.content[0]]?100:0;return 0}
export function journeyNodeStatus(node,recommendedId=null,s=getState()){if(nodeComplete(node.id))return'completed';if(!nodeUnlocked(node))return curriculum.findIndex(item=>item.id===node.id)>curriculum.findIndex(item=>item.id===nextCurriculumNode().id)?'future':'locked';return node.id===recommendedId?'recommended':'available'}
export function journeyMap(s=getState()){const recommendation=recommendNext(s),recommendedId=recommendation.action==='node'?recommendation.nodeId:null;return JOURNEY_CHAPTERS.map(chapter=>({...chapter,progress:Math.round(chapter.nodeIds.map(id=>curriculum.find(node=>node.id===id)).reduce((total,node)=>total+journeyNodeProgress(node,s),0)/chapter.nodeIds.length),nodes:chapter.nodeIds.map(id=>{const node=curriculum.find(item=>item.id===id);return {...node,status:journeyNodeStatus(node,recommendedId,s),progress:journeyNodeProgress(node,s),lockedReason:nodeUnlocked(node)?null:`Complete ${node.requires.map(req=>curriculum.find(item=>item.id===req)?.title||req).join(' and ')} first.`,metadata:{audioAvailable:false,discoveryId:null,artwork:null}}})}))}
export function recommendNext(s=getState()){const active=s.activeSession;if(active){return {action:'resume',title:active.focus?'Continue Focus Quest':`Continue ${active.title||'your journey'}`,reason:'You stopped here last time.',commitment:'Continue where you left off.',nodeId:active.nodeId||null,session:active}}const knownDue=vocabulary.filter(word=>s.reviews?.[word.id]&&(!s.reviews[word.id].due||s.reviews[word.id].due<=Date.now()));const weak=weakWords();const daysAway=s.lastStudy?Math.floor((Date.now()-new Date(s.lastStudy+'T00:00:00').getTime())/DAY):0;if(daysAway>=3&&knownDue.length)return {action:'review',title:'Warm up with familiar Japanese',reason:'These words are ready for a gentle return review.',commitment:'~2 min',items:knownDue.slice(0,5)};if(daysAway>=3)return {action:'focus',title:'Take a gentle first step',reason:'A short Focus Quest is a comfortable way back in.',commitment:'2 min'};const next=curriculum.find(node=>nodeUnlocked(node)&&!nodeComplete(node));if(next)return {action:'node',title:next.title,reason:`${next.title} moves your current chapter forward.`,commitment:next.type==='kana'?'~5 min':next.type==='story'?'~3 min':'~5 min',nodeId:next.id,node:next};if(knownDue.length)return {action:'review',title:'Review what is due',reason:'These items are ready for review.',commitment:'~2 min',items:knownDue.slice(0,5)};if(weak.length)return {action:'mistakes',title:'Strengthen a tricky spot',reason:'These words have been difficult recently.',commitment:'~3 min'};return {action:'focus',title:'Keep your momentum',reason:'A short Focus Quest keeps the path warm.',commitment:'2 min'} }
