const framing=(position,aspectRatio,minHeight)=>({position,aspectRatio,minHeight});

export const SCENES={
  'aoi-shop':{id:'aoi-shop',location:"Aoi's Shop",background:'../assets/shop/aoi-shop-interior.webp',midground:[],foreground:[],focalRegion:'center left',textSafeRegion:'center right',framing:{desktop:framing('50% 50%','auto','230px'),tablet:framing('48% 50%','auto','230px'),mobile:framing('42% 50%','auto','430px')},ambient:'warm-interior',characterSlot:{anchor:'left center',scale:1,desktop:{anchor:'left center',scale:1},mobile:{anchor:'center top',scale:.92}},description:"Aoi's warmly lit cultural shop, with wooden shelves and carefully displayed Japanese objects.",fallback:'warm-interior'},
  'sakura-room':{id:'sakura-room',location:"Sakura's Room",background:'../assets/sakura-room.webp',midground:[],foreground:[],focalRegion:'center',textSafeRegion:'outside-scene',framing:{desktop:framing('50% 50%','16 / 9','360px'),tablet:framing('50% 50%','16 / 10','350px'),mobile:framing('52% 50%','4 / 3','390px')},ambient:'quiet-interior',characterSlot:{anchor:'right bottom',scale:.9,desktop:{anchor:'right bottom',scale:.9},mobile:{anchor:'right bottom',scale:.72}},description:"Sakura's calm room with seven places for displaying cultural objects collected through learning.",fallback:'quiet-interior'},
  'sakura-garden':{id:'sakura-garden',location:'Sakura Garden',background:'../assets/garden/sakura-garden-master.webp',midground:[],foreground:[{id:'foliage-edge',src:'../assets/garden/sakura-garden-foreground.webp',source:'../assets/garden/sakura-garden-foreground.png',kind:'foreground',approved:true}],ambientLayers:[{id:'lantern-light',src:'../assets/garden/sakura-garden-light.webp',source:'../assets/garden/sakura-garden-light.png',kind:'ambient',approved:true},{id:'petals',src:'../assets/garden/sakura-garden-petals.webp',source:'../assets/garden/sakura-garden-petals.png',kind:'ambient',approved:true}],growthOverlays:{early:{id:'growth-early',src:'../assets/garden/sakura-garden-growth-early.webp',source:'../assets/garden/sakura-garden-growth-early.png',kind:'growth',approved:true},growing:{id:'growth-growing',src:'../assets/garden/sakura-garden-growth-growing.webp',source:'../assets/garden/sakura-garden-growth-growing.png',kind:'growth',approved:true},'full-bloom':{id:'growth-full',src:'../assets/garden/sakura-garden-growth-full.webp',source:'../assets/garden/sakura-garden-growth-full.png',kind:'growth',approved:true}},depth:{eligible:true,maxDisplacement:6,safeRegion:'lower right'},focalRegion:'center',textSafeRegion:'lower left',framing:{desktop:framing('50% 50%','16 / 9','430px'),tablet:framing('50% 50%','4 / 3','440px'),mobile:framing('58% 50%','3 / 4','470px')},ambient:'garden-breeze',characterSlot:{anchor:'right bottom',scale:.82,desktop:{anchor:'right bottom',scale:.82},mobile:{anchor:'right bottom',scale:.64}},growthCompatible:{engine:'gardenProgress',states:['early','growing','full-bloom'],mapping:{'1-2':'early','3-4':'growing','5-7':'full-bloom'}},description:'A tranquil moonlit garden whose blossoms and details reflect learning progress.',fallback:'garden-night',artStatus:'approved-layered'}
};

export const SCENE_IDS=Object.freeze(Object.keys(SCENES));
export function sceneById(id){return SCENES[id]||null}
export function sceneFrame(id,viewport='desktop'){const scene=sceneById(id);return scene?.framing?.[viewport]||scene?.framing?.desktop||null}
export function gardenVisualState(level=1){const n=Math.max(1,Math.min(7,Number(level)||1));return n<=2?'early':n<=4?'growing':'full-bloom'}
export function validateScenes(registry=SCENES){const errors=[];for(const [key,scene] of Object.entries(registry)){if(scene.id!==key)errors.push(`${key}: id must match registry key`);for(const field of ['location','background','focalRegion','textSafeRegion','description','fallback'])if(!scene[field])errors.push(`${key}: missing ${field}`);for(const viewport of ['desktop','tablet','mobile']){const frame=scene.framing?.[viewport];if(!frame?.position||!frame?.aspectRatio||!frame?.minHeight)errors.push(`${key}: incomplete ${viewport} framing`)}if(!scene.characterSlot?.anchor||!Number.isFinite(scene.characterSlot?.scale))errors.push(`${key}: incomplete character slot`);for(const layer of [...(scene.midground||[]),...(scene.foreground||[]),...(scene.ambientLayers||[])])if(!layer.id||layer.kind&&!['midground','foreground','ambient'].includes(layer.kind))errors.push(`${key}: invalid optional layer`);if(scene.growthCompatible&&!scene.growthCompatible.engine)errors.push(`${key}: growth compatibility needs a canonical engine`);if(scene.growthOverlays&&!['early','growing','full-bloom'].every(state=>scene.growthOverlays[state]?.src))errors.push(`${key}: incomplete growth overlays`)}return {valid:errors.length===0,errors,count:Object.keys(registry).length}}

const esc=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
export function renderCharacterSlot(character){if(!character)return '';const state=character.state||'neutral',style=`--character-scale:${Number(character.scale)||1};--character-anchor:${esc(character.anchor||'right bottom')}`;return `<div class="scene-character" data-character="${esc(character.id)}" data-character-state="${esc(state)}" style="${style}"><img src="${esc(character.image)}" alt="${esc(character.description||character.id)}" loading="lazy" decoding="async" onerror="this.hidden=true;this.parentElement.classList.add('scene-character-fallback')"></div>`}
const assetUrl=src=>src?.startsWith('../assets/')?`./assets/${src.slice('../assets/'.length)}`:src;
const renderLayer=layer=>layer?.src?`<img class="scene-layer scene-layer-${esc(layer.kind||'foreground')}" data-scene-layer="${esc(layer.id)}" src="${esc(assetUrl(layer.src))}" alt="" aria-hidden="true" loading="lazy" decoding="async">`:'';
export function renderScene({id,className='',content='',character=null,label=null,growthLevel=null}){const scene=sceneById(id);if(!scene)return `<section class="scene-shell scene-missing ${esc(className)}" data-scene="missing" role="img" aria-label="${esc(label||'Illustrated location unavailable')}"><div class="scene-content">${content}</div></section>`;const growth=scene.growthOverlays?.[gardenVisualState(growthLevel)];return `<section class="scene-shell scene-${esc(id)} ambient-${esc(scene.ambient)} ${esc(className)}" data-scene="${esc(id)}" style="--scene-image:url('${esc(assetUrl(scene.background))}')" role="img" aria-label="${esc(label||scene.description)}"><div class="scene-atmosphere" aria-hidden="true"></div>${renderLayer(growth)}${renderLayer(scene.midground?.[0])}${renderLayer(scene.ambientLayers?.[0])}${renderLayer(scene.ambientLayers?.[1])}${renderLayer(scene.foreground?.[0])}${renderCharacterSlot(character)}<div class="scene-foreground" aria-hidden="true"></div><div class="scene-content">${content}</div></section>`}

const sceneTargets=[['aoi-shop','.shopkeeper-card'],['sakura-room','.room-scene'],['sakura-garden','.garden-scene']];
export function mountRegisteredScenes(root=globalThis.document){if(!root?.querySelector)return [];const documentRef=root.ownerDocument||root,mounted=[];for(const [id,selector] of sceneTargets){const host=root.querySelector(selector),scene=sceneById(id);if(!host||host.dataset.scene===id)continue;host.dataset.scene=id;host.dataset.sceneArtStatus=scene.artStatus||'approved';host.classList.add('scene-shell',`scene-${id}`,`ambient-${scene.ambient}`);host.style.setProperty('--scene-image',`url('${assetUrl(scene.background)}')`);host.style.setProperty('--scene-position-desktop',scene.framing.desktop.position);host.style.setProperty('--scene-position-tablet',scene.framing.tablet.position);host.style.setProperty('--scene-position-mobile',scene.framing.mobile.position);if(!host.hasAttribute('aria-label'))host.setAttribute('aria-label',scene.description);if(!host.querySelector(':scope > .scene-atmosphere')){const atmosphere=documentRef.createElement('div');atmosphere.className='scene-atmosphere';atmosphere.setAttribute('aria-hidden','true');host.prepend(atmosphere)}const level=host.dataset.gardenLevel||host.className.match(/garden-level-(\d+)/)?.[1]||1;const growth=scene.growthOverlays?.[gardenVisualState(level)];for(const layer of [growth,...(scene.midground||[]),...(scene.ambientLayers||[]),...(scene.foreground||[])]){if(!layer?.src||host.querySelector(`[data-scene-layer="${layer.id}"]`))continue;const image=documentRef.createElement('img');image.className=`scene-layer scene-layer-${layer.kind||'foreground'}`;image.dataset.sceneLayer=layer.id;image.src=assetUrl(layer.src);image.alt='';image.setAttribute('aria-hidden','true');image.loading='lazy';image.decoding='async';host.append(image)}mounted.push(id)}return mounted}
