const framing=(position,aspectRatio,minHeight)=>({position,aspectRatio,minHeight});

export const SCENES={
  'aoi-shop':{id:'aoi-shop',location:"Aoi's Shop",background:'../assets/shop/aoi-shop-interior.webp',foreground:[],focalRegion:'center left',textSafeRegion:'center right',framing:{desktop:framing('50% 50%','auto','230px'),tablet:framing('48% 50%','auto','230px'),mobile:framing('42% 50%','auto','430px')},ambient:'warm-interior',characterSlot:{anchor:'left center',scale:1,desktop:{anchor:'left center',scale:1},mobile:{anchor:'center top',scale:.92}},description:"Aoi's warmly lit cultural shop, with wooden shelves and carefully displayed Japanese objects.",fallback:'warm-interior'},
  'sakura-room':{id:'sakura-room',location:"Sakura's Room",background:'../assets/sakura-room.webp',foreground:[],focalRegion:'center',textSafeRegion:'outside-scene',framing:{desktop:framing('50% 50%','16 / 9','360px'),tablet:framing('50% 50%','16 / 10','350px'),mobile:framing('52% 50%','4 / 3','390px')},ambient:'quiet-interior',characterSlot:{anchor:'right bottom',scale:.9,desktop:{anchor:'right bottom',scale:.9},mobile:{anchor:'right bottom',scale:.72}},description:"Sakura's calm room with seven places for displaying cultural objects collected through learning.",fallback:'quiet-interior'},
  'sakura-garden':{id:'sakura-garden',location:'Sakura Garden',background:'../assets/sakura-garden.webp',foreground:[],focalRegion:'center',textSafeRegion:'lower left',framing:{desktop:framing('50% 50%','16 / 9','430px'),tablet:framing('50% 50%','4 / 3','440px'),mobile:framing('58% 50%','3 / 4','470px')},ambient:'garden-breeze',characterSlot:{anchor:'right bottom',scale:.82,desktop:{anchor:'right bottom',scale:.82},mobile:{anchor:'right bottom',scale:.64}},growthCompatible:true,description:'A tranquil moonlit garden whose blossoms and details reflect learning progress.',fallback:'garden-night'}
};

export const SCENE_IDS=Object.freeze(Object.keys(SCENES));
export function sceneById(id){return SCENES[id]||null}
export function sceneFrame(id,viewport='desktop'){const scene=sceneById(id);return scene?.framing?.[viewport]||scene?.framing?.desktop||null}
export function validateScenes(registry=SCENES){const errors=[];for(const [key,scene] of Object.entries(registry)){if(scene.id!==key)errors.push(`${key}: id must match registry key`);for(const field of ['location','background','focalRegion','textSafeRegion','description','fallback'])if(!scene[field])errors.push(`${key}: missing ${field}`);for(const viewport of ['desktop','tablet','mobile']){const frame=scene.framing?.[viewport];if(!frame?.position||!frame?.aspectRatio||!frame?.minHeight)errors.push(`${key}: incomplete ${viewport} framing`)}if(!scene.characterSlot?.anchor||!Number.isFinite(scene.characterSlot?.scale))errors.push(`${key}: incomplete character slot`)}return {valid:errors.length===0,errors,count:Object.keys(registry).length}}

const esc=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
export function renderCharacterSlot(character){if(!character)return '';const state=character.state||'neutral',style=`--character-scale:${Number(character.scale)||1};--character-anchor:${esc(character.anchor||'right bottom')}`;return `<div class="scene-character" data-character="${esc(character.id)}" data-character-state="${esc(state)}" style="${style}"><img src="${esc(character.image)}" alt="${esc(character.description||character.id)}" loading="lazy" decoding="async" onerror="this.hidden=true;this.parentElement.classList.add('scene-character-fallback')"></div>`}
export function renderScene({id,className='',content='',character=null,label=null}){const scene=sceneById(id);if(!scene)return `<section class="scene-shell scene-missing ${esc(className)}" data-scene="missing" role="img" aria-label="${esc(label||'Illustrated location unavailable')}"><div class="scene-content">${content}</div></section>`;return `<section class="scene-shell scene-${esc(id)} ambient-${esc(scene.ambient)} ${esc(className)}" data-scene="${esc(id)}" style="--scene-image:url('${esc(scene.background)}')" role="img" aria-label="${esc(label||scene.description)}"><div class="scene-atmosphere" aria-hidden="true"></div>${renderCharacterSlot(character)}<div class="scene-foreground" aria-hidden="true"></div><div class="scene-content">${content}</div></section>`}

const sceneTargets=[['aoi-shop','.shopkeeper-card'],['sakura-room','.room-scene'],['sakura-garden','.garden-scene']];
export function mountRegisteredScenes(root=globalThis.document){if(!root?.querySelector)return [];const documentRef=root.ownerDocument||root,mounted=[];for(const [id,selector] of sceneTargets){const host=root.querySelector(selector),scene=sceneById(id);if(!host||host.dataset.scene===id)continue;host.dataset.scene=id;host.classList.add('scene-shell',`scene-${id}`,`ambient-${scene.ambient}`);host.style.setProperty('--scene-image',`url('${scene.background}')`);host.style.setProperty('--scene-position-desktop',scene.framing.desktop.position);host.style.setProperty('--scene-position-tablet',scene.framing.tablet.position);host.style.setProperty('--scene-position-mobile',scene.framing.mobile.position);if(!host.hasAttribute('aria-label'))host.setAttribute('aria-label',scene.description);if(!host.querySelector(':scope > .scene-atmosphere')){const atmosphere=documentRef.createElement('div');atmosphere.className='scene-atmosphere';atmosphere.setAttribute('aria-hidden','true');host.prepend(atmosphere)}mounted.push(id)}return mounted}
